### ISSUE TITLE
Front-end mouse-over editing options & article editing tabs disappearing

### ISSUE THREAD

**Issue by atfs** [JoomShaper/Helix3#10]
I have noticed that when trying to creat/edit an article from the front-end, when I click on a tab, it disappears when the option to "Mouse-over Edit Icons for" (Site settings) is set to "None" (either using the template only or the quickstart).

**Comment by nayemmajhar** [comment]
bug fixed. check now. https://github.com/JoomShaper/Helix3/commit/b2c1347d73be804b2edc206ef14247509478ed49

**Comment by atfs** [comment]
Thank you!
