### ISSUE TITLE
Problem with Presets tab inside the template configuration

### ISSUE THREAD

**Issue by bigflipo** [JoomShaper/Helix3#12]
hello, the program works fine but the presets tab has problems.
there are 4 preset divs which show the colors of the template.
when I select them, the template changes color the way it sould.
but when I tweak the styling options, the divs update color but the changes are not reflected in the template, the default color is the one appearing.
example: the third preset div has the major color green, if I change the value in the styling options to black and save, the div turns to black but the template will still be green.

very nice program I like it a lot.

**Comment by rifatwahid** [comment]
Hi,
Please make sure that: Compile LESS to CSS is Enabled from Advanced tab in helix template option.

- Thanks

**Comment by bigflipo** [comment]
Thank you rifawahid that made the trick.
