### ISSUE TITLE
Protect category name and tags from disappearance 

### ISSUE THREAD

**Issue by pfrankowski** [JoomShaper/Helix3#15]
after hover on it when mootools are enabled in Helix3 template by module or plugin.
Problem is here:  templates\helix3\js\main.js
Here is ready fix by Jola Surma from Polish Joomla Community (big thanks):
File: 
[main.zip](https://github.com/JoomShaper/Helix3/files/68447/main.zip)

I will compare those two files and will tell more about changes.

This is short movie about which problem I'm taking about:
[znik1.zip](https://github.com/JoomShaper/Helix3/files/67142/znik1.zip)

**Comment by pfrankowski** [comment]
More details from Jola sourcecode:
    //Tooltip
  //  $('[data-toggle="tooltip"]').tooltip();

//zmiana
$('[data-toggle="tooltip"]').on('mouseleave', function(e){
    e.stopImmediatePropagation();
    $("div").find("[role='tooltip']").hide();
  }).tooltip();
// koniec zmiana

**Comment by bertmert** [comment]
I think this should be fixed in mootools-more or by extension/template providers that still use Mootools. Not in Joomla or Joomla extensions that don't use it.
It's not a tooltips issue only. Also Bootstrap 3 Dropdowns and Bootstrap 3 Collapse (buttons) are affected.

**Comment by nayemmajhar** [comment]
solved
