### ISSUE TITLE
Kunena forum topic icons radio buttons not aligned

### ISSUE THREAD

**Issue by darrylxxx** [JoomShaper/Helix3#16]
I am using Helix that came with j-Directory. I installed Kunena forum. When creating a new topic, my icons were vertically aligned. I now have them horizontal thanks to https://www.joomshaper.com/edit-profile/little-problem-with-forum-integration#reply-41733. However the radio buttons with the Topic Icons are all to the right of the icons i.e. they are not related to the correct icon.

**Comment by skurvish** [comment]
I have this same issue. Here is a screen shot: http://prntscr.com/ba9xka
This is what it should look like: http://prntscr.com/ba9y1y

**Comment by nayemmajhar** [comment]
@skurvish you can fix using below code. This is CSS with Kunena dependency. So we will not add this in the file. I will merge your pull request soon.

```
#Kunena img {
  display: block;
  float: left;
  max-width: none !important;
}
```

**Comment by skurvish** [comment]
I already have this css applied as mentioned by darryl above we have both applied this css but now exhibit the problem as shown in the screen images.

**Comment by nayemmajhar** [comment]
could you share site URL here

**Comment by skurvish** [comment]
Is there a means to provide login details privately? Can I send them to your email address in your profile?

**Comment by nayemmajhar** [comment]
Okay. Send to me at nayemmajhar@gmail.com

**Comment by skurvish** [comment]
For the benefit of others who might come here, nayem was unable to determine the cause of this problem.

**Comment by skurvish** [comment]
With thanks to my nephew:

#Kunena input[type="radio"] {
    float: left;
    margin: 10px 5px 0 0;
}
#Kunena .kiconsel img {
    margin: 0 10px 0 0;
}

**Comment by nayemmajhar** [comment]
Great.

**Comment by umuarama999** [comment]
The below code worked pretty fine here.
Thanks!

#Kunena img {
  display: block;
  float: left;
  max-width: none !important;
}
