### ISSUE TITLE
Links in off canvas menu not working on iphone/mobile devices

### ISSUE THREAD

**Issue by itsme85** [JoomShaper/Helix3#18]
Hello, I'm building a website with an offcanvas menu. The problem is that the off canvas menu is not clickable the first time (it is not active) on my iphone and ipad. It works on the second click only. Could someone help me with this?

Kind regards

**Comment by nayemmajhar** [comment]
Could you share your site link and let us check. Must mention the version of helix3.

**Comment by itsme85** [comment]
Thank you very munch for your reply. 

Tried to figure out the problem for many hours. Just on coming in of your reply, I found the solution. 

The mobile canvas is only working in the online, non developing mode. Tried before when it didn't work, now it does!

**Comment by nayemmajhar** [comment]
Great. But it works in all mode.

**Comment by itsme85** [comment]
In my case it doesn't. I use the Helix3 template in Joomla. When the website is offline and I login, the off canvas is not working on my mobile devices. Tried it in a very empty joomla version, joomla and the helix template only, but still the same problem.
