### ISSUE TITLE
Problem with backend saving in joomla 3

### ISSUE THREAD

**Issue by matosss** [JoomShaper/Helix3#19]
Hi,

i encountered a problem, where i cant edit and save anything while working from joomla backend in Helix3. I want to edit my current copyright state, i can change it, but i cant save it.
What can be done?

With best regards

**Comment by rifatwahid** [comment]
Hi,
You meant you can't save any data from helix template settings? if is it then try our new version of helix3. hope your problem will be solved by new version.

- Thanks
