### ISSUE TITLE
No Helix Blog Options Tab in Articles Feature

### ISSUE THREAD

**Issue by lstocky** [JoomShaper/Helix3#21]
![helix blog options not showing](https://cloud.githubusercontent.com/assets/17546863/13395028/01e448cc-dee4-11e5-8236-bb67674963d7.png)

I have installed Helix 3 - the plugins and template on Joomla! 3.4.8 Stable. However, as show in the above screenshot, I am not seeing the Helix Blog Options Tab in the articles feature.

I'm wondering if the install didn't quite go to plan. Does anyone have any suggestions?

If you need more info from me please let me know what's needed to assist.

many thanks
lstocky

**Comment by rifatwahid** [comment]
Hi.
Could you please make sure that helix plugin is enabled?

- Thanks

**Comment by lstocky** [comment]
Hey - thanks for the help. 

Here's what I see. 



Sent from my mobile

On 29 Mar 2016, at 10:51, Rifat wahid ALIF <notifications@github.com> wrote:

Hi.
Could you please make sure that helix plugin is enabled?

Thanks

**Comment by rifatwahid** [comment]
alright,
please knock in our live chat and refer me here. our support team will solve it.
