### ISSUE TITLE
helix3 menu and falang

### ISSUE THREAD

**Issue by rintynator** [JoomShaper/Helix3#23]
i use joomla 3.5 and falang and the helix3 framework. I have three languages. If i change the language, the menu shows the correct translations - thats fine. But the menu also show entires which are not translated or activated for the chosen language. Is this correct? Is this a falang or a helix3 menu problem? Thanks for your support.

**Comment by ionut2014** [comment]
Hi,
I work with both and i see that everything is ok.

If your lang is english, so if you visit another lang let's say spanish, in spanish you will see what you have translated and what you dont have translated, you will see in english.

**Comment by rintynator** [comment]
Yes, that works for me too.
But i don´t want show the menu entries which are not translated / activated for e.g. spanish.
But i think this is not work with falang?

**Comment by ionut2014** [comment]
Hi, That's only from falang. This is their method for translate.. You can't hide something.
