### ISSUE TITLE
Bt content  images not loading from helix blog

### ISSUE THREAD

**Issue by ionut2014** [JoomShaper/Helix3#24]
Hello,
Bt content http://bowthemes.com/joomla-extensions/bt-content-slider.html have an issue with helix: Id i have in articleon helix blog option an image or more images, bt not shown images. Is working only with joomla images

**Comment by rifatwahid** [comment]
Hi,
In helix 1.2 version we have added sp media manager. so need to change some codes for getting image.

you can see our codes from here: **templates/shaper_helix3/html/layouts/joomla/content/intro_image.php**

- Thanks
