### ISSUE TITLE
Trouble whit the sharing of the pictures and content with facebook

### ISSUE THREAD

**Issue by mignolo1977** [JoomShaper/Helix3#25]
Good evening!
I m having a trouble to sharing the content and the images of my articles blog. This looks to happen since i upgrade my SP PageBuilder pro to the 1.0.8 version. As you can see for exemple in one of my blog page: 

http://www.psicoterapiapsicoanalitica.net/area-clinica/tempi-duri-per-i-fumatori-regole-pesanti-dal-2-febbraio.html

if you try to share content through face book button the image and the content shared from facebook are always linked to the homepage and not properly of the article i want to share !( this not happen with other social ). When i try to Fetch new scrape information from Facebook debug (https://developers.facebook.com/tools/debug/og/object/) it always show the image and contentent link to my home page made with SP Page Builder Pro (where of course i complete by filling with open graph setting).
Thank you for helping me!
Joseph

**Comment by nayemmajhar** [comment]
https://www.facebook.com/groups/819713448150532/ discuss here please
