### ISSUE TITLE
Disappearing Menu Items in Front-End

### ISSUE THREAD

**Issue by stuartjbaker** [JoomShaper/Helix3#26]
Hi,

Using Helix3 on Joomla v3.4.8 and getting this exact issue. User logs in on front-end and tries to add event (Jevents extension) and each 'tab' disappears once clicked on.

edit.php contents matches code from the bug fix.

Bug occurrence or am I missing something?

Thanks,

**Comment by stuartjbaker** [comment]
Any ideas anyone?

**Comment by nayemmajhar** [comment]
Please open Joomla Debug mode and check error for helix plugin.
No bug in Helix3, please discuss your issue here https://www.facebook.com/groups/819713448150532/ lots of people here help each others.
