### ISSUE TITLE
smooth scroll to the section (sp page builder + helix3)

### ISSUE THREAD

**Issue by zrymov** [JoomShaper/Helix3#28]
1) how to make a smooth scroll to the section?
  I Now when you press the jump instantly to the specified anchor.
and when you click "Home" again progruzhat site (non-refundable)
when you try to change to an external url Home gives an error:
"Warning
Save failed with the following error: The home menu item must be a component ".
I am using sp page builder + helix3
2) how to make that site when scrolling, selection menu item smoothly flows, depending on where on the page is now nahodishsya in XEON or Acrostia example?
http://demo.joomshaper.com/?template=xeon (demo site for clarity)

**Comment by pepperstreet** [comment]
This video and file attachment might help you: 
(Cudos to Toufiqur Rahman)
https://www.youtube.com/watch?v=rPEs_svP7dY

**Comment by zrymov** [comment]
Thank's a lot!
It helps very much!
tell me how to make a smooth return to the "home"?
when i press the "home" I have to re-load the site.

**Comment by zrymov** [comment]
how to align portfolio centered on the whole width?
I did not set the width of the small portfolio pictures and put a check on the item Fluid Row.
but portfolio not the entire width and alignment of the left
site: 
http://test.33bokala.ru

**Comment by nayemmajhar** [comment]
hey @zrymov please discuss customization or other things in helix community group here https://www.facebook.com/groups/819713448150532/ lots of people help each others. You can create an issue for bugs or send pull request here.

**Comment by zrymov** [comment]
Thanks
