### ISSUE TITLE
Fatal error menu.php line 461

### ISSUE THREAD

**Issue by skurvish** [JoomShaper/Helix3#29]
Getting Fatal error: Call to a member function get() on a non-object in /var/www/html/plugins/system/helix3/core/classes/menu.php on line 461
Happens because there is no object $params in this function, it is $item->params. Making this change solves the problem.

**Comment by nayemmajhar** [comment]
Thanks you

**Comment by skurvish** [comment]
This issue has resurfaced in the most recent 1.7 update. The same error exists now on line 472. In fact there is an additional issue; Line should read:

output .= 'toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,' .     $item->params->get('window_open');

Note the $output rather than $option and the same issue with the $item->params
