### ISSUE TITLE
article publication date disappear

### ISSUE THREAD

**Issue by prankyboy** [JoomShaper/Helix3#3]
Hello
template builded using joomshaper+helix3 (no pagebuilder)
duplicate template
when mouse hover article publication date it disappear.

**Comment by nayemmajhar** [comment]
http://helix-framework.org/ Here is our community forum. You can discuss there with other member. BTW, pagebuilder is the cool things that integrated with helix 3, i think you will love it too.

**Comment by qbikowski** [comment]
ok but what about solving this problem?

**Comment by nayemmajhar** [comment]
We solved this issue. Please use latest version of helix3

**Comment by qbikowski** [comment]
ok I had ver 1.2 installed from github and it hide date the same as before

**Comment by nayemmajhar** [comment]
Use development version. Fix added after version 1.2.
