### ISSUE TITLE
anchor_css not assigned to single item menu's

### ISSUE THREAD

**Issue by skurvish** [JoomShaper/Helix3#30]
In file: plugins/system/helix3/core/classes/menu.php function item around line 419 if there is no $extra_class passed to this function then the menu defined anchor_css is not applied to the menu link.

I have change this:
$item->anchor_css = ($item->anchor_css) ? ' ' . $item->anchor_css : '';
$class = ($class) ? 'class="' . $class . $item->anchor_css . '" ' : '';
to this:
$sep = ($class != '' && $item->anchor_css != '') ? ' ' : '';
$class = ($class != '' || $item->anchor_css != '') ? 'class="' . $class . $sep . $item->anchor_css . '"' : '';

Problem is corrected.

**Comment by skurvish** [comment]
Actually Bertmerts pull request of Nov 18 solves this better. I did not see it before posting this.

**Comment by nayemmajhar** [comment]
639ef83bd394bf1f4e3b53df0c5f5162337447cf merged
