### ISSUE TITLE
Joomla 3.5.1 removal of Menu Title Issues

### ISSUE THREAD

**Issue by fuzmic2** [JoomShaper/Helix3#33]
Hi guys

I have Helix3 in Joomla 3.5.1, it works great, easy to use, no hitch.  Still hoping the SP Page Builder & its very clean look SP Simple Portfolio and be included in the Joomla Search.

My issue is in this is:
I can't remove the Menu Title included in a Joomla Article.  I would also like to control the appearance of yellow the Pin it at top and the bottom social objects (see attached jpg)
![article](https://cloud.githubusercontent.com/assets/16586815/15694319/2ec13290-27cf-11e6-9858-ada306ad083c.jpg)

**Comment by skurvish** [comment]
Did you disable the menu title in the menu itself?

What is it you want to do with the pin? Use firebug or chrome developer tools to get the class of the icon and you can style it using your custom.css file.

**Comment by nayemmajhar** [comment]
This is not a bug report or enhancement request. Please discuss to get help https://www.facebook.com/groups/819713448150532/
