### ISSUE TITLE
Bug in Macro template.  Setting background color does not work.

### ISSUE THREAD

**Issue by carukc** [JoomShaper/Helix3#35]
I'm not sure why I should have to report this here since the bug has already been confirmed by your support staff? See here: https://www.joomshaper.com/forums/template-style-background-color-does-not-seem-to-be-working

Anyway...  In the Macro template (and perhaps others)...  I have changed the background color in the template style but cannot find this color anywhere in the generated page. The "Major Color" seems to work but not the "Background Color". I've tried to clear cache as recommended in other posts but it still does not seem to work.

This has been confirmed by Toufiq as a bug and he has posted a solution on the JoomShaper support site on the URL noted above.

**Comment by nayemmajhar** [comment]
Please follow Joomshaper Forum
