### ISSUE TITLE
Custom Javascript

### ISSUE THREAD

**Issue by easypony** [JoomShaper/Helix3#37]
Hi

I created a custom.js and added it to the js folder as specified. It was not being included. 

As a workaround I have had to add it using the template method and renamed it functions.js it does load this way. 

Not ideal as it will be overridden on an update not sure why it did not pick up custom.js

Steve

**Comment by pepperstreet** [comment]
Good point! Thought this issue has been reported and solved already... apparently not. Thanks for reminding. I totally agree with you.  

It should behave like the custom CSS functionality:  
One option is the template style parameter. 
Second option is an external file named **custom.JS**

**Comment by nayemmajhar** [comment]
https://github.com/JoomShaper/Helix3/commit/db6fdd37d56e32bd6a6a9a912af4fde76e784f5d
