### ISSUE TITLE
"Helix Blog Options" tab not available when editing from frontend

### ISSUE THREAD

**Issue by woluweb** [JoomShaper/Helix3#40]
NB : this concerns all Helix3 templates

One of the big advantages I see in Helix templates is the famous "Helix Blog Options" tab in the Articles, (allowing people to easily add videos, images etc, with a nice & uniform layout for the whole site).
All Helix3-based templates take advantage of that in the front-end layout with nice Joomla Template Overrides.

But unfortunately, that tab is NOT available when editing from front-end...
... that is particularly sad because end-users _do_ edit from front-end, not from back-end.

Could you please correct for this in the next version (or tell how can I workaround already) ?

Txs & keep up the good work :-)

**Comment by nayemmajhar** [comment]
Did you update helix3 to latest version.

**Comment by woluweb** [comment]
Yes, latest version, namely :
System - Helix3 Framework : 1.2
(coming along with JoomShaper Macro 1.3)

Joomla Update Manager does not show any available update
(and I guess that the Helix3 Framework plugin ships with the Macro template or on his own)

Why ?
Do *you* get the "Helix Blog Options" tab in front-end ?

Txs,
Marc

**Comment by nayemmajhar** [comment]
Please mention your Joomla version? Why didn't ask for premium support? You
are using a premium template.

**Comment by woluweb** [comment]
Latest version of Joomla 3.6.2.
Premium support ? I don't see any menu named "premium support" on joomshaper.com (only "Support Forum")

**Comment by woluweb** [comment]
(by the way, this is precisely the followup of
https://www.joomshaper.com/forums/helix-blog-options-tab-not-available-when-editing-from-frontend
where Toufiq asked me to post on your github :-)

**Comment by nayemmajhar** [comment]
@woluweb will be added. @rifatwahid please note this.

**Comment by woluweb** [comment]
Txs ! Looking forward to this :-)

**Comment by mtif** [comment]
I am keen to see this new feature as it would make my Joomla site as easy as Wordpress for my users (and this is something I constantly hear them request).

**Comment by woluweb** [comment]
Not yet present in Helix v1.7 which has just been released...
"Helix Blog Options" tab is great/excellent/super for non-tech people.
So why keeping that tab only accessible from back-end, and not on front-end ? :-)

**Comment by nayemmajhar** [comment]
Guys, we will add this in version 1.8. Most of the team member involve in building SP Page Builder Version 2. Thanks for constant suggestions.

**Comment by woluweb** [comment]
Txs Naeyem Majhar !
That is great news indeed.
Not just for me, for all users.
Because indeed, when I make a demo to a prospect, that front-end edition will be very much convincing :-)

**Comment by Vityushka** [comment]
Hi guys! I know, that this issue already closed, so just interest - when can we expect version 1.8? Blog option in front-end - this is really question of life and death. Thank you!

**Comment by woluweb** [comment]
Hi ! It seems that this is not yet integrated. Can you tell us more about the roadmap ? When will it be integrated. Helix Blog Options is great, but if it can't be used from front-end, it is almost useless for most end-users...
Txs !

**Comment by nayemmajhar** [comment]
Will be added in upcoming version.

**Comment by woluweb** [comment]
Excellent !
Txs :-)

**Comment by nayemmajhar** [comment]
https://github.com/JoomShaper/Helix3/commit/50663875ef1efbbf30d69b1ee585571cf4af6f29 added

**Comment by woluweb** [comment]
By the way : now that the file template/html/com_content/form/edit.php has been edited for the Template Helix... I guess that the other templates will also get the same improvement for their next release ?
(or is the improvement de facto integrated via the Helix *framework* ? I don't think so, since it seems that an override of template/html/com_content/form/edit.php is needed)
