### ISSUE TITLE
Validation w3-issues

### ISSUE THREAD

**Issue by payothemes** [JoomShaper/Helix3#41]
Hi,
Please see https://validator.w3.org/nu/?doc=http%3a%2f%2fdemo.joomshaper.com%2f2015%2fhelix3%2f

I have my theme build on helix and i have the same errors on validating.Can you help me to validate all?

Ps i made a theme based on helix 3, and it was rejected because of this validate w3.  Errors are the same as helix default.  Please see  validation from start.  Helix or page builder have those errors. 

Can you help me to fix them? Those regarding h1-h6...

**Comment by rifatwahid** [comment]
Hi,
We fixed all error in helix3. Rest of the issue comes from **SP Pagebuilder** we will fix it in next update.


- Thanks
