### ISSUE TITLE
Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by 810** [JoomShaper/Helix3#43]
Warning: A non-numeric value encountered in C:\wamp\www\develop\plugins\system\helix3\core\helix3.php on line 489

**Comment by nayemmajhar** [comment]
Did you check [Helix3 1.7] (https://www.joomshaper.com/downloads/template/helix3) ? Let me know, is still that happen?

**Comment by nayemmajhar** [comment]
Follow this issue https://github.com/JoomShaper/Helix3/issues/58

**Comment by 810** [comment]
i don't see the message anymore.

**Comment by nayemmajhar** [comment]
team is working and will be added soon.
