### ISSUE TITLE
sp-header has wrong position with columns above

### ISSUE THREAD

**Issue by gregorvogel** [JoomShaper/Helix3#44]
The "sp-header" has now a fixed position. This doesn't work i have other columns above "sp-header". For example put the "Page Title" above the "Header" in the Layout.

If i set the
`#sp-header {    position: relative;} `
Then the page jumps as soon as the header gets sticky.

A possible solution would be:
Set the "sp-header" into a div container with "position: relative;" and the same height as the "sp-header" (like you had it on the earlier version "sp-header-sticky-wrapper")

**Comment by pepperstreet** [comment]
Following...

**Comment by rifatwahid** [comment]
Hi,
In 1.5 we have removed **Sticky Plugin** dependency. we wrote js code for sticky header. it won't wrap **sp-header-sticky-wrapper** div. because some people facing problem on animation for this plugin. you can use it if you want from previous version.

- Thanks

**Comment by gregorvogel** [comment]
I just installed a new clean Joomla version with the newest Helix3.
If you scroll down a few pixels (when the #sp-header gets the sticky with the class "menu-fixed") then the whole page jumps up for 90 Pixels. This is very annoying.

This is because the the "#sp-header.menu-fixed" changes the "position" to "fixed".
A Wrapper Div could slove the problem. Maybe you have a better solution.

**Comment by rifatwahid** [comment]
we will update it in next version.
