### ISSUE TITLE
Mega-Menu: Menu-Heading contains Link to Main-Page! Possible Solution attached

### ISSUE THREAD

**Issue by trailsnail** [JoomShaper/Helix3#47]
Hey there,

if I create a menu-heading for showing my menues in columns, then the headings are assigned with a a-href via class Helix3Menu. Found this "bug" written somewhere in the web while looking for a solution.
The workaround you will see in the attachement is not the best solution if you want to look good for googles crawlers. But this was the only way to prevent redirecting a visitor caused from clicking on a menu-heading.

So I looked a little bit for myself, and found out, that it seems to be inconsistent in class Helix3Menu on Line 86: "do nothing, if we have separator or heading" against Line 463, where you render a Link into the HTML independently from type of item.

I think you have to check the itemtype at this lines too.

Here the bad workaround for the user:
![menu-heading](https://cloud.githubusercontent.com/assets/4742603/19417899/89d80f32-93b8-11e6-81a3-95072af3aac7.jpg)

And here the solution I use atm.
![my-solution](https://cloud.githubusercontent.com/assets/4742603/19417908/df135e3e-93b8-11e6-88ab-0c61ed0aed84.jpg)

**Comment by nayemmajhar** [comment]
Sound interesting. Could you send me some reference about this issue with Google crawlers. I want to know more about it.

**Comment by ioweb-gr** [comment]
Hi, I stumbled into this today as well. I got a similar solution to @trailsnail however I wrapped the `switch` clause under the `else` condition because imho separators and headings should never become links under any circumstances. Even if we forget the SEO part due to the links appearing, the user experience is also important because if they click the links, they get redirections.

```php
        $output = '';
        if ($item->params->get('menu_show', 1) != 0) {
            if (($item->type == 'separator') || ($item->type == 'heading')) {
                $output .= '<span ' . $class . '>' . $linktitle . '</span>';
            } else {
                switch ($item->browserNav) {
                    default:
                    case 0:
                        $output .= '<a ' . $class . ' href="' . $flink . '" ' . $title . '>' . $linktitle . '</a>';
                        break;
                    case 1:
                        $output .= '<a ' . $class . ' href="' . $flink . '" target="_blank" ' . $title . '>' . $linktitle . '</a>';
                        break;
                    case 2:
                        $options .= 'toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,' . $params->get('window_open');
                        $output .= '<a ' . $class . ' href="' . $flink . '" onclick="window.open(this.href,\'targetWindow\',' . $options . ');return false;" ' . $title . '>' . $linktitle . '</a>';
                        break;
                }
            }
        }

```

**Comment by rifatwahid** [comment]
are you talking about external URL menu? we will fix this issue no problem when you will select menu type as menu heading then it won't get anchor tag anymore.

- Thanks

**Comment by nayemmajhar** [comment]
https://github.com/JoomShaper/Helix3/commit/db6fdd37d56e32bd6a6a9a912af4fde76e784f5d
