### ISSUE TITLE
Page Jumps after scrolling 90 pixels down

### ISSUE THREAD

**Issue by gregorvogel** [JoomShaper/Helix3#48]
I just installed a new clean Joomla version with the newest Helix3.
If you scroll down a few pixels (when the #sp-header gets the sticky with the class "menu-fixed") then the whole page jumps up for 90 Pixels. This is very annoying.

This is because the the "#sp-header.menu-fixed" changes the "position" to "fixed".
A Wrapper Div could slove the problem. Maybe you have a better solution.

**Comment by rifatwahid** [comment]
we will update this in next version

- Thanks

**Comment by nayemmajhar** [comment]
Fixed. Download from http://joomshaper.com or update in your site.
