### ISSUE TITLE
Kunena incompatibility

### ISSUE THREAD

**Issue by micker** [JoomShaper/Helix3#5]
hello helix 3 isn't compatible with crypsis ...
Fatal Error was detected!
The error was detected in the System - Helix3 Plugin.
Fatal Error: Cannot redeclare class lessc_formatter_compressed in plugins/system/helix3/core/classes/lessc.inc.php on line 3666
... some idea ?

**Comment by nayemmajhar** [comment]
Did you upgrade your helix to latest version?

**Comment by micker** [comment]
i am in 1.1 jan 2015

**Comment by micker** [comment]
i update it's better no fatal error but CSS are horrible ... and no main menu ...
http://www.android2ee.com/Index.html
do you have an idea ?
regards

**Comment by nayemmajhar** [comment]
no css added. just make it kunena compatible

**Comment by micker** [comment]
ok i will try new crypis template version
but why no main menu ????

**Comment by nayemmajhar** [comment]
Select menu from template manager to show.

**Comment by micker** [comment]
it doesnt work only on kunena view 
all other page work

**Comment by nayemmajhar** [comment]
discus here please http://helix-framework.org/

**Comment by micker** [comment]
see here
http://helix-framework.org/no-menu-on-kunena-view
