### ISSUE TITLE
In Helix3 v1.5 and v1.6 , Offcanvas submenus are no longer displayed

### ISSUE THREAD

**Issue by fynhooft** [JoomShaper/Helix3#50]
Hi,

First I installed the latest version of helix3_quickstart_j3_v1.6 to see why it works for Joomshaper and not for my website.
In fact, instead of putting links "separator" in the sub-menus titles , Joomshaper use a "external url" that points to "#".
So, I replace my separators with the same type of link and it works (except for last link which is not displayed! )

If, in helix3_quickstart_j3_v1.6, I replace, for example in the Joomla menu -> content component, "external URL" with "Text Separator" than I generate the same mistake.

It is indeed a bug in the file templates /shaper_helix3/html/mod_menu/default.php but I do not know what to fix.

**Comment by rifatwahid** [comment]
Hi,
We have fixed ** separator** and **alias** menu offcanvas issue, you will get it in next update. hopefully today.

- Thanks

**Comment by nayemmajhar** [comment]
@fynhooft Version 1.7 released. Update now and check.
