### ISSUE TITLE
Error Code - 1054 

### ISSUE THREAD

**Issue by leslieongit** [JoomShaper/Helix3#51]
Unknown column 'i.language' in 'on clause' SQL=SELECT c.id, c.asset_id, c.access, c.alias, c.checked_out, c.checked_out_time, c.created_time, c.created_user_id, c.description, c.extension, c.hits, c.language, c.level, c.lft, c.metadata, c.metadesc, c.metakey, c.modified_time, c.note, c.params, c.parent_id, c.path, c.published, c.rgt, c.title, c.modified_user_id, c.version, CASE WHEN CHAR_LENGTH(c.alias) != 0 THEN CONCAT_WS(':', c.id, c.alias) ELSE c.id END as slug,COUNT(i.`id`) AS numitems FROM chdg4_categories as c LEFT JOIN `chdg4_auction_products` AS i ON i.`catid` = c.id AND (i.language = '*' OR i.language = 'en-GB') WHERE (c.extension='com_auction' OR c.extension='system') AND c.access IN (1,1,5) AND c.language in ('en-GB','*') GROUP BY c.id, c.asset_id, c.access, c.alias, c.checked_out, c.checked_out_time, c.created_time, c.created_user_id, c.description, c.extension, c.hits, c.language, c.level, c.lft, c.metadata, c.metadesc, c.metakey, c.modified_time, c.note, c.params, c.parent_id, c.path, c.published, c.rgt, c.title, c.modified_user_id, c.version ORDER BY c.lft
![image](https://cloud.githubusercontent.com/assets/14816994/19686411/4d3e4324-9ac1-11e6-81fe-e0b6e27c6052.png)
d, c.version ORDER BY c.lft

**Comment by nayemmajhar** [comment]
This is not a major issue, it will not hurt you. It's just commenting syntax mistake in Language file. We will fix this issue in next update.

**Comment by leslieongit** [comment]
Thanks, will patiently wait for the update for the future website.
