### ISSUE TITLE
Bug when using Joomla FrontEnd Images and Links tab

### ISSUE THREAD

**Issue by mtif** [JoomShaper/Helix3#52]
I am building a site using your Brezz Pro Quickstart, latest version.  Joomla is updated to 3.6.4
I actually need Helix Blog options for FrontEnd editors, but I know this is only a requested new feature at the moment.
In the short term I have tried to enable Joomla standard 'Images and Links' Tab in the Joomla config. When I now edit in the frontend I can see the 'Images and Links' tab, but if i select it a blank modal screen covers over the whole page. There is no way to get out, but to back page.

**Comment by rifatwahid** [comment]
Hi,
**Brezz Pro** is not our template. Maybe they used our **Helix3 Framework**.  Could you please post here screenshots which problem are you facing?

- Thanks

**Comment by mtif** [comment]
My apologies, I had thought you were associated with the template. Yes it uses Helix 3, but its from Joomlead and I have passed issue to them. But looking forward to 1.9 release of Helix and front end Blog Options. 
Thanks
