### ISSUE TITLE
Magnific Popup is not compatible with Helix 1.7.

### ISSUE THREAD

**Issue by Krabtus** [JoomShaper/Helix3#53]
Magnific Popup is not compatible with Helix 1.7.
Between the Framework Helix3 v.1.7 and Phoca Gallery creates a Script Error in the Detailed view "Magnific pop (image only). If at the Phoca Gallery Detailed view" Magnific pop (image only) "selected template with an active Helix3, is the image is not displayed in a lightbox but in a tab. http://dimsemenov.com/plugins/magnific-popup/
The problem, you can look at themselves in this screenshot.
![screenshot](https://cloud.githubusercontent.com/assets/23345178/20115427/825cc9bc-a5f8-11e6-89a1-a5989efb23fa.jpg)

**Comment by nayemmajhar** [comment]
Phoca Gallery compatibility will check.

**Comment by nayemmajhar** [comment]
Use the latest version of Helix3 with Phoca Gallery. In my side, it is working fine ( I checked in Google Chrome, Firefox and Safari )
