### ISSUE TITLE
Button, links and Labels are disappearing in frontend

### ISSUE THREAD

**Issue by Kamixo** [JoomShaper/Helix3#55]
In K2 and Kunena in the frontend, links, buttons, tabs and etc disappear after hover. After hover always comes "display: none". This problem applies to almost any extension. I can fix it partially, by using css "display: ...! Important". But this is not the correct solution.

**Comment by nayemmajhar** [comment]
please follow this issue https://github.com/JoomShaper/Helix3/issues/56

**Comment by nayemmajhar** [comment]
Issue fixed https://github.com/JoomShaper/Helix3/commit/c215eeb16e968edbf6b67b6be76dcd90602a9b7b
