### ISSUE TITLE
Browser Page Title

### ISSUE THREAD

**Issue by assafbarr** [JoomShaper/Helix3#59]
Custom browser title (Menus>Edit Item>Page Display>Browser Page Title) is not showing when the menu item type is a single article, the article's title is shown instead
Joomla 3.6.5 - Helix3 1.8

**Comment by assafbarr** [comment]
We need to change the code line number 39 in this file :
shaper_helix3/html/com_content/article/default.php
Instead of: $document->setTitle($this->item->title);
it should be: $document->setTitle($this->params->get('page_heading'));

**Comment by assafbarr** [comment]
I have noticed that the site name (Global Configuration->Site->Site Name) is not appearing

**Comment by drbeat** [comment]
> shaper_helix3/html/com_content/article/default.php
Instead of: $document->setTitle($this->item->title);
it should be: $document->setTitle($this->params->get('page_heading'));

that line is unnecessary. it just breaks the title-tag...
