### ISSUE TITLE
Helix Framework uses http calls to "fonts.googleapis.com" which prevents full https validation for website

### ISSUE THREAD

**Issue by Mika83AC** [JoomShaper/Helix3#61]
Hello everyone,

as we switched our websites to HTTPS, we stumbled over an issue with a
template which makes use of the helix framework.

Helix makes hard coded calls to http://font.googleapis.com/... . This is no
problem until you're not using your website with HTTPS. But if you use it
with HTTPS, you get an insecure resources issue which can easily prevented
by calling httpS://fonts.googleapis.com insead of the HTTP version.

So i'd like to request this change in the helix plugin in the
core/helix.php file in function "public static function GoogleFont($name,
$field)".

Thx.

Regards,
Michael

**Comment by nayemmajhar** [comment]
Noted
