### ISSUE TITLE
left column together with 2 or more right columns

### ISSUE THREAD

**Issue by FlorianGeorgiev** [JoomShaper/Helix3#62]
Hello there, could this be achieved:
```
<div class="left_columnt">
<div class="right_column">
<div class="slider"> </div>
<div class="Content_area"> </div>
</div>
</div>
```
So I have one left column, in the right of that column I have one slider and the content area, which are not on the whole width of the site. This could be easily achieved with Content Builder but it doesn't support the Content Area, so I want to achieve that structure with the Helix3 framework.

Please help.

**Comment by nayemmajhar** [comment]
Add a screenshot to understand clearly

**Comment by FlorianGeorgiev** [comment]
![image1](https://cloud.githubusercontent.com/assets/25362724/22372420/378472f0-e4a5-11e6-933e-8ae43baa8a03.JPG)

as simple as that

**Comment by pepperstreet** [comment]
Hello Florian, 
are we talking about a PageBuilder layout in Joomla main content area? 
Or is "left side" a regular Joomla sidebar position?  

--- 

What about 1 Row and 2 simple Columns? Should work for your graphic/mockup.

If you need more Columns on the "Right" in "Content Area", you would need PageBuilder **PRO**. It allows to create **Nested Rows**. In other words, content area is another Row, which can consist of multiple Columns.

**Comment by nayemmajhar** [comment]
Nested row in helix3 will be added soon.

**Comment by FlorianGeorgiev** [comment]
Ah, OK, this is what I asked for.
Thanks

2017-02-10 7:43 GMT+02:00 Nayem Majhar <notifications@github.com>:
