### ISSUE TITLE
Helix blog options front-end: You are not authorised to upload files

### ISSUE THREAD

**Issue by Vityushka** [JoomShaper/Helix3#66]
If I try to upload something in gallery (for example) with user without admin rights I got "You are not authorised to upload files". As I know Blog Options no have any security settings from back-end.
Btw yet one error: authoriSed -> authoriZed

**Comment by nayemmajhar** [comment]
Please check media upload permission for that user.

**Comment by Vityushka** [comment]
Works. Thank you.

**Comment by pepperstreet** [comment]
Good point and topic! 

IMHO, the blog options definitely need Category restrictions (incl. or excl. certain Categories), 
and even better: ACL support and parameters for each option. Comparable to ACL tab in PageBuilder AddOns.
