### ISSUE TITLE
Version 1.9 release are different from site and Github

### ISSUE THREAD

**Issue by horus68** [JoomShaper/Helix3#68]
Last release on Github for v1.9 has the same code as the zip download from the site. This is supposed to be the exact same code if same version, true?

Files
\plugins\system\core\classes\menu.php
(too many lines to detail)

\template\templateDetails.xml
(copyright year on github is older)

JoomShaper/Helix3 Version: 1.9
- Github download - https://github.com/JoomShaper/Helix3/releases/tag/1.9
- Site Download: https://www.joomshaper.com/joomla-templates/helix3

**Comment by pepperstreet** [comment]
Github project seems to be not maintained/updated ?! 
Currently we have 2.0 as official release and download, but Github has no release 2.0 at all. 
Isn't the purpose of Github to have releases/milestones/ and even an updated "master" as a "work-in-progress"?

**Comment by horus68** [comment]
There is an update now for 2.0 :)
https://github.com/JoomShaper/Helix3/releases/tag/v2.0
