### ISSUE TITLE
Duplicate attribute title on share buttons

### ISSUE THREAD

**Issue by casettabio** [JoomShaper/Helix3#70]
Hi,
when you enable the share buttons the w3c validator show 2 issues: Duplicate attribute title.
The dublicated title are on Google plus and on Linkdin.
Thanks a lot for a fix

**Comment by drbeat** [comment]
I can not reproduce the issue.
Do you have a screenshot or a link?

**Comment by casettabio** [comment]
Hi,
Here you are a screen shot from w3c validator.
The online page is 
https://www.gmonamour.it/
Tanks a lot, my best regards
Antonio
![senza-titolo-1](https://cloud.githubusercontent.com/assets/27723784/25374367/6ce1223a-299d-11e7-916c-8f276fe20f8c.jpg)

**Comment by drbeat** [comment]
did you try updating to v2.0 ?

**Comment by casettabio** [comment]
Hi,
yes, now the bugs is fixed!
Thanks!
