### ISSUE TITLE
Warning at non-numeric value

### ISSUE THREAD

**Issue by costafrancesco94** [JoomShaper/Helix3#78]
Hi :)
I just installed an Helix3 template in Joomla, and i have XDebug active on my development server.

I noticed that the plugin is throwing a php warning in the file
`plugins/system/helix3/core/helix3.php` at line `490` saying that he has found a non-numeric value.

The issue can be easily solved by placing a cast to int on `$last_col` (becouse `$last_col = ""` and not `0`)

So the line coul be:
`$column->className = 'col-sm-' . (self::getColXsNo($column->className) + (int) $last_col) . ' col-md-' . (self::getColXsNo($column->className) + (int) $last_col);`

I have only installed the template, so there are no settings or modules, the page is half empty, but i like to render the page without PHP can compain about anything... If you think this doesn't break up your code I suggest you to insert this little edit in your next commit...

**Comment by rifatwahid** [comment]
We already fixed this issue. Please update helix3 plugin.
