### ISSUE TITLE
Helix3 v2.4 needs security fix for modules.php

### ISSUE THREAD

**Issue by pepperstreet** [JoomShaper/Helix3#85]
Hello, Joomla 3.8.4 included a security fix for a modules chrome tag parameter! They advised all template/framework developers to check and update the **modules.php** file. Read details here:
https://docs.joomla.org/J3.x:Joomla_3.8.4_Notes_about_the_Security_Patches 

So, this issue applies to Helix3 itself **and** all Helix3 based templates!
See latest System and Protostar template folder for fix. Seem to by 1 line only.

Thanks in advance.

**Comment by nayemmajhar** [comment]
@pepperstreet Thank you. fixed added eeff026f868dd5954fe9c7115a52e7718f50c931
