### ISSUE TITLE
Google fonts subset issue

### ISSUE THREAD

**Issue by schizo-ri** [JoomShaper/Helix3#9]
When adding Google Font URL you should add 'subset=' string.

I solved this for myself by modifing /plugins/system/helix3/core/helix3.php on line 815.

```php
$subset = array_unique( $value['subset'] );
if(isset($subset) && $subset) {
    $output .= '&amp;subset=' . implode(',', $subset);
    }
```

I'm not sure if this is a good solution.

**Comment by nayemmajhar** [comment]
we already fixed this issue. Use update version of Helix3
