### ISSUE TITLE
Call to a member function get() on null

### ISSUE THREAD

**Issue by asfaqueali** [JoomShaper/Helix3#90]
https://github.com/JoomShaper/Helix3/blob/1393307d92a70bd4526125764d5eeaf8fd123bc8/plugins/system/core/helix3.php#L83

Issue while clicking on preview button of sppagebuilder pages

![image](https://user-images.githubusercontent.com/28622177/36150460-cf778cd4-10e9-11e8-8f87-31c3b7a88701.png)

**Comment by asfaqueali** [comment]
@nayemmajhar please look into it

**Comment by asfaqueali** [comment]
It's working with latest sppagebuilder but only on those pages which are linked with any menu item, and those which are not linked has the same error

**Comment by Suse75** [comment]
Same problem here after update. That is very annoying.

**Comment by rifatwahid** [comment]
Hi,
Thanks for your report. We have already fixed this issue. Could you please give a try this: [https://github.com/JoomShaper/Helix3/commit/7ae78d47f2c89f2f20e27bd9b4dc21315938e4e4](url)

- Thanks

**Comment by asfaqueali** [comment]
Yes, thanks its resolved
