### ISSUE TITLE
Helix3 Layout

### ISSUE THREAD

**Issue by asfaqueali** [JoomShaper/Helix3#91]
When I save template layout all positions set to none.

![image](https://user-images.githubusercontent.com/28622177/36188649-592c9a8a-1173-11e8-9c69-eb2122683820.png)

@nayemmajhar can you please look into it

**Comment by pepperstreet** [comment]
Just out of curiosity, are you talking about the select-box in upper left corner? 
Are you able to load the default layout again?  
Did you check the saved layout files location? ( See .JSON files in _YourHelixTemplate/layout/.._ )
Does it save the actual JSON file? If yes, is it empty?

**Comment by asfaqueali** [comment]
Hi, its resolved now actually the problem was with my helix system plugin
